name: Build Flutter web

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Flutter web app to github pages
    # You may pin to the exact commit or the version.
    # uses: erickzanardo/flutter-gh-pages@93439c0fa94838d5abdf1e783f7383e9fa609e66
      uses: erickzanardo/flutter-gh-pages@v1
      with:
      # If the build should use skia (canvas kit) or not (default false)
        useCanvasKit: true # optional
